apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: todo
        image: abhishekf5/todo-app:v1
        ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
          nodePort: 31006
